[workspace]

members = [
    "aoc",
    "day_one",
    "day_two",
    "day_three",
    "day_four",
    "day_five",
    "day_six",
    "day_seven",
    "day_eight",
    "day_nine",
    "day_ten",
    "aoc_2023/day_one_trebuchet",
]